In [1]:
import pandas as pd

In [18]:
df = pd.read_html('https://www.nestpick.com/millennial-city-ranking-2018/', index_col= '#', skiprows=0)[0]
df.columns = ['city', 'country','Employment', 'Startup', 'Tourism','Housing', 'Food Ranking', 'Transport', 'Health Ranking', 'Internet Speed', 'University', 'Access to Contraceptive', 'Gender Equality', 'Immigration Tolerence', 'Personal Freedom and Choice', 'LGBT friendly', 'Nightlife', 'Beer Ranking', 'Festival Ranking', 'Total']
df.index.name= None
df.head()

city         country  Employment  Startup  Tourism  Housing  \
1     Berlin         Germany         4.8      9.0      6.2      5.2   
2   Montréal          Canada         6.0      8.1      5.7      6.4   
3     London  United Kingdom         6.6      9.8      9.8      0.5   
4  Amsterdam     Netherlands         7.6      8.3      8.7      0.6   
5    Toronto          Canada         6.3      9.5      4.4      2.7   

   Food Ranking  Transport  Health Ranking  Internet Speed  University  \
1           7.2        7.1             3.9             5.0         4.9   
2           5.1        3.6             7.4             5.1         5.8   
3           2.2        7.2             4.4             4.7        10.0   
4           1.7        5.7             6.9             4.5         5.0   
5           6.1        4.3             7.4             7.1         5.2   

   Access to Contraceptive  Gender Equality  Immigration Tolerence  \
1                      6.9              7.5                    8.4   
2                      8.6              7.0                    9.9   
3                      9.5              7.1                    8.7   
4                      7.9              5.5                    8.5   
5                      8.6              7.0                    9.9   

   Personal Freedom and Choice  LGBT friendly  Nightlife  Beer Ranking  \
1                          7.8            9.7       10.0           7.0   
2                          8.1            9.6        8.8           5.1   
3                          9.6            9.4        9.4           2.5   
4                         10.0            9.9        8.6           4.8   
5                          9.4            9.8        4.5           3.6   

   Festival Ranking  Total  
1               8.0   7.14  
2               9.0   7.10  
3               7.5   6.71  
4               9.7   6.63  
5               9.4   6.60

In [25]:
new_df = df.set_index('city').drop('country', axis=1)

In [26]:
new_df.head()

Employment  Startup  Tourism  Housing  Food Ranking  Transport  \
city                                                                        
Berlin            4.8      9.0      6.2      5.2           7.2        7.1   
Montréal          6.0      8.1      5.7      6.4           5.1        3.6   
London            6.6      9.8      9.8      0.5           2.2        7.2   
Amsterdam         7.6      8.3      8.7      0.6           1.7        5.7   
Toronto           6.3      9.5      4.4      2.7           6.1        4.3   

           Health Ranking  Internet Speed  University  \
city                                                    
Berlin                3.9             5.0         4.9   
Montréal              7.4             5.1         5.8   
London                4.4             4.7        10.0   
Amsterdam             6.9             4.5         5.0   
Toronto               7.4             7.1         5.2   

           Access to Contraceptive  Gender Equality  Immigration Tolerence  \
city                                                                         
Berlin                         6.9              7.5                    8.4   
Montréal                       8.6              7.0                    9.9   
London                         9.5              7.1                    8.7   
Amsterdam                      7.9              5.5                    8.5   
Toronto                        8.6              7.0                    9.9   

           Personal Freedom and Choice  LGBT friendly  Nightlife  \
city                                                               
Berlin                             7.8            9.7       10.0   
Montréal                           8.1            9.6        8.8   
London                             9.6            9.4        9.4   
Amsterdam                         10.0            9.9        8.6   
Toronto                            9.4            9.8        4.5   

           Beer Ranking  Festival Ranking  Total  
city                                              
Berlin              7.0               8.0   7.14  
Montréal            5.1               9.0   7.10  
London              2.5               7.5   6.71  
Amsterdam           4.8               9.7   6.63  
Toronto             3.6               9.4   6.60

In [27]:
from sklearn.metrics.pairwise import cosine_similarity

In [30]:
data = cosine_similarity(new_df)

In [31]:
cos = pd.DataFrame(data, columns=new_df.index, index = new_df.index)

In [32]:
cos.head()

city         Berlin  Montréal    London  Amsterdam   Toronto  Vancouver  \
city                                                                      
Berlin     1.000000  0.975863  0.938963   0.947773  0.951332   0.922286   
Montréal   0.975863  1.000000  0.941389   0.961700  0.975247   0.957213   
London     0.938963  0.941389  1.000000   0.973298  0.936199   0.910812   
Amsterdam  0.947773  0.961700  0.973298   1.000000  0.957828   0.942885   
Toronto    0.951332  0.975247  0.936199   0.957828  1.000000   0.988505   

city       Barcelona  New York City   Cologne  Manchester  ...     Milan  \
city                                                       ...             
Berlin      0.968329       0.919555  0.966253    0.957443  ...  0.800487   
Montréal    0.966475       0.912072  0.945366    0.966261  ...  0.806269   
London      0.916010       0.973668  0.867689    0.932517  ...  0.827142   
Amsterdam   0.944275       0.956883  0.894119    0.938235  ...  0.816657   
Toronto     0.939639       0.911270  0.903554    0.944347  ...  0.761663   

city         Venice    Bergen  Cape Town  Innsbruck      Bern  Jerusalem  \
city                                                                       
Berlin     0.733084  0.720674   0.783029   0.803423  0.747877   0.723305   
Montréal   0.806221  0.781280   0.768051   0.826466  0.803055   0.792246   
London     0.685502  0.717978   0.620739   0.696071  0.777343   0.699456   
Amsterdam  0.746991  0.727588   0.638335   0.729730  0.801031   0.739133   
Toronto    0.737904  0.810103   0.739925   0.815524  0.814025   0.760868   

city         Brugge    Geneva   Bologna  
city                                     
Berlin     0.762560  0.752925  0.730900  
Montréal   0.810103  0.802312  0.818431  
London     0.721481  0.790703  0.686889  
Amsterdam  0.743057  0.807565  0.751788  
Toronto    0.801673  0.842894  0.801049  

[5 rows x 110 columns]

In [49]:
cos.iloc[0,:].sort_values(ascending=False)[1:].idxmax()

'Vienna'

In [53]:
import numpy as np

In [63]:
others = np.random.choice(range(1,11),17)

In [71]:
df.iloc[:,2:-1].round(0).astype(int).head()

Employment  Startup  Tourism  Housing  Food Ranking  Transport  \
1           5        9        6        5             7          7   
2           6        8        6        6             5          4   
3           7       10       10        0             2          7   
4           8        8        9        1             2          6   
5           6       10        4        3             6          4   

   Health Ranking  Internet Speed  University  Access to Contraceptive  \
1               4               5           5                        7   
2               7               5           6                        9   
3               4               5          10                       10   
4               7               4           5                        8   
5               7               7           5                        9   

   Gender Equality  Immigration Tolerence  Personal Freedom and Choice  \
1                8                      8                            8   
2                7                     10                            8   
3                7                      9                           10   
4                6                      8                           10   
5                7                     10                            9   

   LGBT friendly  Nightlife  Beer Ranking  Festival Ranking  
1             10         10             7                 8  
2             10          9             5                 9  
3              9          9             2                 8  
4             10          9             5                10  
5             10          4             4                 9

In [56]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 110 entries, 1 to 110
Data columns (total 20 columns):
city                           110 non-null object
country                        110 non-null object
Employment                     110 non-null float64
Startup                        110 non-null float64
Tourism                        110 non-null float64
Housing                        110 non-null float64
Food Ranking                   110 non-null float64
Transport                      110 non-null float64
Health Ranking                 110 non-null float64
Internet Speed                 110 non-null float64
University                     110 non-null float64
Access to Contraceptive        110 non-null float64
Gender Equality                110 non-null float64
Immigration Tolerence          110 non-null float64
Personal Freedom and Choice    110 non-null float64
LGBT friendly                  110 non-null float64
Nightlife                      110 non-null float64
Beer Ranking 

In [70]:
great = df.iloc[:,2:-1].round(0).astype(int)
great.head()

Employment  Startup  Tourism  Housing  Food Ranking  Transport  \
1           5        9        6        5             7          7   
2           6        8        6        6             5          4   
3           7       10       10        0             2          7   
4           8        8        9        1             2          6   
5           6       10        4        3             6          4   

   Health Ranking  Internet Speed  University  Access to Contraceptive  \
1               4               5           5                        7   
2               7               5           6                        9   
3               4               5          10                       10   
4               7               4           5                        8   
5               7               7           5                        9   

   Gender Equality  Immigration Tolerence  Personal Freedom and Choice  \
1                8                      8                            8   
2                7                     10                            8   
3                7                      9                           10   
4                6                      8                           10   
5                7                     10                            9   

   LGBT friendly  Nightlife  Beer Ranking  Festival Ranking  
1             10         10             7                 8  
2             10          9             5                 9  
3              9          9             2                 8  
4             10          9             5                10  
5             10          4             4                 9

In [75]:
berlin = great.iloc[0,:].values

In [64]:
others

array([ 4,  9,  7,  9,  9,  9,  6,  3,  5,  5,  3,  8,  4,  3, 10,  2,  7])

In [93]:
cosine_similarity(others.reshape(-1,17),berlin.reshape(-1,17))

array([[0.90884259]])

In [69]:
great.iloc[0,2:-1].values()

Tourism                         6
Housing                         5
Food Ranking                    7
Transport                       7
Health Ranking                  4
Internet Speed                  5
University                      5
Access to Contraceptive         7
Gender Equality                 8
Immigration Tolerence           8
Personal Freedom and Choice     8
LGBT friendly                  10
Nightlife                      10
Beer Ranking                    7
Name: 1, dtype: int64

In [77]:
berlin.shape

(17,)

In [78]:
others.shape

(17,)

In [85]:
import math
def cosim(x, y):
    
    """x and y are arrays / vectors"""
    
    num = 0
    for movie in great.columns:
        num += x[movie] * y[movie]
        
#     num = np.dot(x.values, y.values)
        
    xnorm = math.sqrt(sum(x ** 2))
    ynorm = math.sqrt(sum(y ** 2))
    
    denom = xnorm * ynorm
    
    return num/denom

In [86]:
cosim(others, berlin)

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [87]:
great.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 110 entries, 1 to 110
Data columns (total 17 columns):
Employment                     110 non-null int64
Startup                        110 non-null int64
Tourism                        110 non-null int64
Housing                        110 non-null int64
Food Ranking                   110 non-null int64
Transport                      110 non-null int64
Health Ranking                 110 non-null int64
Internet Speed                 110 non-null int64
University                     110 non-null int64
Access to Contraceptive        110 non-null int64
Gender Equality                110 non-null int64
Immigration Tolerence          110 non-null int64
Personal Freedom and Choice    110 non-null int64
LGBT friendly                  110 non-null int64
Nightlife                      110 non-null int64
Beer Ranking                   110 non-null int64
Festival Ranking               110 non-null int64
dtypes: int64(17)
memory usage: 20.5 KB


In [88]:
berlin

array([ 5,  9,  6,  5,  7,  7,  4,  5,  5,  7,  8,  8,  8, 10, 10,  7,  8])

In [89]:
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np
vec1 = np.array([[1,1,0,1,1]])
vec2 = np.array([[0,1,0,1,1]])
#print(cosine_similarity([vec1, vec2]))
print(cosine_similarity(vec1, vec2))

[[0.8660254]]


In [91]:
berlin = np.array([[ 5,  9,  6,  5,  7,  7,  4,  5,  5,  7,  8,  8,  8, 10, 10,  7,  8]])
others = np.array([[  4,  9,  7,  9,  9,  9,  6,  3,  5,  5,  3,  8,  4,  3, 10,  2,  7]])
cosine_similarity(others, berlin)

array([[0.90884259]])

In [92]:
berlin.shape

(1, 17)

In [94]:
new = np.array([[  4,  9,  7,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 0,  2,  7]])
cosine_similarity(new, berlin)

array([[0.50755304]])

In [95]:
berlin = np.array([[ 5,  9,  6,   7,  8]])
new = np.array([[  4,  9,  7,  2,  7]])
cosine_similarity(new, berlin)

array([[0.94554668]])

In [96]:
new_df.loc['Berlin']

Employment                      4.80
Startup                         9.00
Tourism                         6.20
Housing                         5.20
Food Ranking                    7.20
Transport                       7.10
Health Ranking                  3.90
Internet Speed                  5.00
University                      4.90
Access to Contraceptive         6.90
Gender Equality                 7.50
Immigration Tolerence           8.40
Personal Freedom and Choice     7.80
LGBT friendly                   9.70
Nightlife                      10.00
Beer Ranking                    7.00
Festival Ranking                8.00
Total                           7.14
Name: Berlin, dtype: float64